### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/LegalDocs#7]
>## What we collect when you use Adguard DNS
### When you use Adguard DNS, it sees the following information:
* Your IP-address.
* DNS request which contains domain name.
We, in our turn, do not log or save any information. Since no information is being saved, nothing is sent to third parties.

Does this mean, precisely, that logging is disabled? Or that data is retained, in some sort of anonymized form, for a specific limited time period before being wiped? Is it ever turned on for purposes debugging and/or attack mitigation?

I raise these questions because to some, like myself, the wording used may seem vague. Not logging or saving information isn’t the same thing as logs being completely disabled.

**Comment by ameshkov** [comment]
Should be re-phrased indeed.

First of all, it is not "what we collect", but "what we receive on the server side". We cannot avoid receiving it.

> Does this mean, precisely, that logging is disabled?

Yes.

> Or that data is retained, in some sort of anonymized form, for a specific limited time period before being wiped?

Aggregated form: total requests count, avg. requests per sec, etc. It has nothing to do with the personal data, though, just performance metrics.

**Comment by X8716e** [comment]
@ameshkov , Thank-you for the clarification.

**Comment by el-termikael** [comment]
seems to be resolved in the current version of the Privacy Policy: https://adguard-dns.io/en/privacy.html
